theme:
    page_title: "DSC 10"


listings: !include listings.yaml


buttons:
    top:
        - text: Syllabus
          subtext: FAQ, etc.
          url: ./syllabus.html
          icon: em-blue_book

        - text: Office Hours
          subtext: Calendar
          url: ./office_hours.html
          icon: em-hourglass_flowing_sand

        - text: Campuswire
          subtext: Message Board
          url: www.campuswire.com
          icon: em-mega

        - text: Gradescope
          subtext: Gradebook
          url: www.gradescope.com
          icon: em-bar_chart

    bottom:
        - text: Textbook
          subtext: Dive into Data Science
          url: http://diveintods.com
          icon: em-blue_book

        - text: All Resources
          subtext: Calendar
          url: ./resources.html
          icon: em-hourglass_flowing_sand


schedule:
    # what should the first week be numbered?
    first_week_number: 0

    # what is the first day of the first week? this is used to determine the
    # start and end of each subsequent week
    first_week_start_date: 2020-09-28

    exams:
        Midterm 01: 2020-10-15
        Midterm 02: 2020-11-22
        Final Exam: 2020-12-01

    # a list of the quarter's topics, week by week. the number of weeks will be
    # inferred from this list
    week_topics:
        - Introduction
        - Tables
        - Charts and Functions
        - Probability and Simulation
        - Statistics and Models
        - Hypothesis Testing
        - The Bootstrap
        - The Normal Curve
        - Regression
        - Conclusion
        - Finals Week

    week_announcements:
        - week: 0
          content: |
              ### Welcome to DSC 10

              Here's how to get started:

              - read the [syllabus](./syllabus.html)
              - join our [campuswire](http://campuswire.com) with access code 231234
              - join our [gradescope](http://gradescope.com) with access code 901281

              See you in lecture.
              

    lecture:
        
        # what collection contains lectures?
        collection: lectures

        # what metadata key contains the lecture's date? this is used to place
        # the lecture into the correct week
        metadata_key_for_released: date

        # what should be displayed as the lecture's title? template string.
        title: "Lecture ${ publication.metadata.number } &mdash; ${ publication.metadata.topic }"

        # what resources are available for each lecture?
        resources:
            - 
              # the 
              text: "<a href=${ publication.artifacts['lecture.ipynb'].path }>Lecture Notebook</a>"
              icon: em-notebook

            - text: 'Reading: <a href="http://diveintods.com">Dive into Data Science</a>'
              icon: em-book
        parts:
            key: videos
            text: '<a href="${ part.url }">${ part.title }</a>'

    assignments:

        - collection: projects
          metadata_key_for_released: released
          metadata_key_for_due: due
          title: "Project"
          resources:
              - text: "Notebook"
                requires:
                    artifact: project.ipynb

        # homeworks
        - 
          # what collection contains the assignment?
          collection: homeworks

          # what metadata key contains the homework's release date? this is
          # used to place the assignment in the correct week.
          metadata_key_for_released: released

          # what metadata key contains the assignment's due date?
          metadata_key_for_due: due

          # what should be displayed as the assignment's title? template string.
          title: "Homework ${ publication.metadata.number }"

          # what resources are available for each assignment?
          resources:
              
              # homework notebooks
              - text: "<a href=${ publication.artifacts['homework.txt'].path }>Homework Notebook</a>"
                icon: em-question
                requires:
                    artifact: homework.txt
                    text_if_missing: Not released yet...

              # solution notebooks
              - text: "<a href=${ publication.artifacts['solution.txt'].path }>Solution Notebook</a>"
                icon: em-mag
                #
                # do not display this resource if the following artifact doesn't exist
                requires:
                    artifact: solution.txt

    discussions:

        -
            collection: discussions
            metadata_key_for_released: date
            title: 'Discussion ${ publication.metadata.number }'

            resources:
                - text: <a href="${ publication.artifacts['discussion.ipynb'].path }">Discussion Notebook</a>
                  icon: em-notebook
                  requires:
                      artifact: discussion.ipynb
