logo: logo.png
title: {{ course.name }}
instructor: {{ course.instructor }}


urgent_announcement:
    type: warning
    content: |
        This is a warning! Please submit CAPEs ASAP!



schedule:
    # dictionary mapping each week to an announcment
    weekly-announcements:
        1: This is a test! Warning! Hello!
        4: No homework this week!

    # a list of topics, one per week
    weekly_topics:
        - Introduction
        - Tables
        - Charts and Functions
        - Probability and Simulation
        - Statistics and Models
        - Hypothesis Testing
        - The Bootstrap
        - The Normal Curve
        - Regression
        - Conclusion

        homeworks:
            # what collection are these drawn from?
            from_collection: homeworks

            # what metadata field should be used to place this within the schedule?
            date_field: metadata.released

            # what metadata field should be used to determine its due date?
            due_date_field: metadata.due

            # what to display if the week is here but the homework doesn't
            on_missing: Homework not released yet.

            # what to display as the title
            title: "Homework << number >>"

            # list of things that should be displayed for the homework
            resources:
                # problems
                - icon: none
                  content: '<a href="<< artifacts.homework.path >>">Problems</a>'

                # solutions
                - icon: none
                  content: '<a href="<< artifacts.solution.path >>">Solutions</a>'

                # latex template
                - icon: none
                  content: '<a href="<< artifacts.template.path >>">Template</a> and <a>instructions</a>'

        labs:
            from_collection: labs
            date_field: metadata.released
            due_date_field: metadata.due
            on_missing: Lab not released yet.

            title: "Lab << number >>"

            resources:
                lab:
                    icon: none
                    content: '<a href="<< artifacts.lab.path >>">Lab Notebook</a>'
                solution:
                    icon: none
                    content: '<a href="<< artifacts.solution.path >>">Solutions</a>'

        projects:
            from_collection: projects
            date_field: metadata.released
            due_date_field: metadata.due
            on_missing: Project not released yet.

            title: "Project << number >>"

            resources:
                lab:
                    icon: none
                    content: '<a href="<< artifacts.lab.path >>">Lab Notebook</a>'
                solution:
                    icon: none
                    content: '<a href="<< artifacts.solution.path >>">Solutions</a>'

    presentations:

        lectures:
            from_collection: lectures
            date_field: metadata.date

            title: "Lecture << number >>: << metadata.title >>"

            resources:
                watch_party:
                      icon: eyes
                      content: "Watch Party on << metadata.date >> at 4:00 PM PST"
                reading:
                      icon: book
                      content: "Recommended reading: 40B Notes"
                slides:
                      icon: none
                      content: '<a href="<< artifacts.slides.path >>">Lecture Slides</a>'

            parts:
              numbered: true
              iterate: metadata.videos

        discussions:
            from_collection: discussions
            date_field: metadata.date

            title: "Discussion << number >>"

            resources:
                watch_party:
                    icon: eyes
                    content: "Watch Party on << metdata.date >> at 4:00 PM PST"
                reading:
                    icon: book
                    content: "Recommended reading: 40B Notes"


listings:
    - page: homeworks.html
      collection: homeworks
      columns:
          - title: Homework
            content: metadata.name
            url: artifacts.homework.path

          - title: Solution
            content: metadata.name
            url: artifacts.solution.path

          - title: Due
            content: metadata.due

listings:
    page: listings

navbar: !include navbar.yaml
listings: !include listings.yaml
schedule: !include schedule.yaml

navbar:
    - text: Syllabus
      subtext: FAQ, grading, etc.
      icon: something
      url: ./syllabus.html

    - text: Gradescope
      subtext: FAQ, grading, etc.
      icon: something
      url: www.gradescope.com/{{ course.gradescope_code }}

    - text: Gradescope
      subtext: FAQ, grading, etc.
      icon: something
      url: www.gradescope.com/{{ course.gradescope_code }}

    - text: Gradescope
      subtext: FAQ, grading, etc.
      icon: something
      url: www.gradescope.com/{{ course.gradescope_code }}

    - text: Gradescope
      subtext: FAQ, grading, etc.
      icon: something
      url: www.gradescope.com/{{ course.gradescope_code }}

    - text: Gradescope
      subtext: FAQ, grading, etc.
      icon: something
      url: www.gradescope.com/{{ course.gradescope_code }}

    - text: Gradescope
      subtext: FAQ, grading, etc.
      icon: something
      url: www.gradescope.com/{{ course.gradescope_code }}
