theme:
    page_title: "DSC 40 &mdash; Fall 2020"


announcement:
    # title is optional; make it Null to display no title
    title: Welcome to DSC 10

    # place contents here; if Null, no box is displayed
    contents: Null

    # if True, make it red
    urgent: False


buttons:
    top:
        - text: Syllabus
          subtext: FAQ, etc.
          url: ./syllabus.html
          icon: em-blue_book

        - text: Office Hours
          subtext: Calendar
          url: ./office_hours.html
          icon: em-hourglass_flowing_sand

        - text: Campuswire
          subtext: Message Board
          url: www.campuswire.com
          icon: em-mega

        - text: Gradescope
          subtext: Gradebook
          url: www.gradescope.com
          icon: em-bar_chart

    bottom:
        - text: Textbook
          subtext: Dive into Data Science
          url: ./syllabus.html
          icon: em-blue_book

        - text: All Resources
          subtext: Calendar
          url: ./resources.html
          icon: em-hourglass_flowing_sand


listings:
    homework:
        collection: homeworks
        numbered: true
        columns:
            - name: Problems
              content: "${ metadata.name }"
              url: "${ artifacts['homework.txt'].path }"

            - name: Solutions
              content: Solution
              url: "${ artifacts['solution.txt'].path }"
              on_missing: "not yet posted"

            - name: Due
              content: "${ metadata.due.strftime('%A, %b %d at %H:%M:%S') }"
